import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { MenuIcon } from "lucide-react";
import { navbarMenuItems } from "@/utils/helpers/navbar";
import NavbarDropdownItem from "@/components/Navbar/NavbarDropdownItem";
const Navbar = () => {
    return (_jsxs("header", { className: "flex h-20 w-full shrink-0 items-center px-4 md:px-6", children: [_jsxs(Sheet, { children: [_jsxs("div", { className: "flex justify-between items-center w-full lg:hidden", children: [_jsx(Link, { to: "/", className: "mr-6 flex", children: _jsx("span", { className: "font-semibold", children: "M.J.T.Solution s.r.o." }) }), _jsx(SheetTrigger, { asChild: true, children: _jsxs(Button, { variant: "outline", size: "icon", children: [_jsx(MenuIcon, { className: "h-6 w-6" }), _jsx("span", { className: "sr-only", children: "Toggle navigation menu" })] }) })] }), _jsxs(SheetContent, { side: "left", children: [_jsx(Link, { to: "/", className: "mr-6 hidden lg:flex", children: _jsx("span", { children: "M.J.T.Solution s.r.o." }) }), _jsx("div", { className: "grid gap-2 py-6", children: navbarMenuItems.map((item) => item.subItems.length ? (_jsx(NavbarDropdownItem, { isMobile: true, item: item }, `dropdown-menu-mobile-item-${item.href}`)) : (_jsx(Link, { to: item.href, className: "flex w-full items-center py-2 text-lg font-semibold", children: item.name }, `nav-mobile-item${item.href}`))) })] })] }), _jsx(Link, { to: "/", className: "mr-6 hidden lg:flex", children: _jsx("span", { className: "font-semibold", children: "M.J.T.Solution s.r.o." }) }), _jsx("nav", { className: "ml-auto hidden lg:flex gap-3", children: navbarMenuItems.map((item) => item.subItems.length ? (_jsx(NavbarDropdownItem, { item: item }, `dropdown-menu-mobile-item-${item.href}`)) : (_jsx(Link, { to: item.href, className: "group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50", children: item.name }, `nav-item${item.href}`))) })] }));
};
export default Navbar;
